### ISSUE TITLE
Message sending checklist

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#26]
Bare minimum stuff to do to send messages through the system (no auth etc):

- [x] Add /createRoom endpoint (don't bother with http auth, send to room server) #32 #33 
- [x] Add /send endpoint (don't bother with http auth, send to room server) #39 
- [x] Add /state endpoint (don't bother with http auth, send to room server) #41
