### ISSUE TITLE
Make sytest's application service tests pass

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#531]
- [x] 01as-create - #528 #532 #533 #534 - barring v1 registration (supporting?) and #427
- [ ] 02ghost - Depends heavily on #427
- [ ] 03passive
- [ ] 04asuser
- [ ] 05lookup3pe - blocked on spec PR for https://github.com/matrix-org/matrix-doc/issues/1203 (wip)
- [ ] 06publicroomlist
- [ ] 07deactivate

**Comment by Kegsay** [comment]
I don't mind having a "are-we-synapse-ready-yet?" issue to track parity with Synapse, but I do object to having lots of issues for this. Please keep issues Specific, Measurable, Achievable/Actionable, Realistic, and Time-Bounded.
