### ISSUE TITLE
Client API checklist

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#8]
This issue aggregates outstanding client API issues that need to be implemented **in order to get dendrite up and running**. It does not consider other components, nor does it consider any bugs or additional feature requests.

- [x] Implement HTTP routing (#11)
- [x] Implement HTTP request ID tracking (`Context` package). Related: implementing the logging framework. (#12)
- [ ] Implement stub HTTP endpoints for all CS API paths (only r0?) - Message sending is done now.
- [ ] Glue stub HTTP endpoints through to roomserver code (or equiv)
- [ ] Implement idempotent PUTs (transaction cache)
- [ ] Implement auth checks (extracting tokens from requests and verifying them, NOT room auth checks)
- [ ] Implement version control on HTTP endpoints (assuming we will Get Serious with `r0`, `r1`, etc in the future, if not then we might as well not bother with this)
- [ ] Implement extensible registration / login code (given how popular it was to extend Synapse's registration code, we should probably think about this from the get-go)
- [ ] Implement open ID (required for Riot Integrations)

There's also some fairly low-hanging non-room-server fruit which could be tackled:
 - [ ] Implement filter APIs (#63)
 - [ ] Implement content repo (#59)
 - [ ] Implement account data APIs (requires notifications between devices) (#60)
 - [ ] Implement push rules APIs (requires notifications between devices)
 - [ ] Implement device management APIs (requires notifications between devices and room membership state)

Do we want to think about QoS from the get-go (to make sure we can't end up with disasters like "a random user at 03:54am decides to sync from aeons ago which cripples the server"). This should be tractable in Go if we decide from the start how to do this (e.g. Bundling QoS factors into `Context`: needs discussion).

**Comment by Kegsay** [comment]
Closing in favour of the google docs spreadsheet.
